### ISSUE TITLE
Github repo about deploying Sentiment Analysis model deleted, how did you save yours?

### ISSUE THREAD

**Issue by EmreTokyuez** [oliverproud/PyTorch-Sentiment-Analysis-deployed-with-Flask#1]
I followed the tutorial from https://github.com/bentrevett/pytorch-sentiment-analysis but I can't manage to deploy it. I don't know what to save and how. Could you share that part of your code if possible?

**Comment by oliverproud** [comment]
Thank you for pointing this out to me, I will update the README. 

To deploy the trained model and its interface to Google Cloud Run using the Dockerfile, please see [here](https://cloud.google.com/run/docs/quickstarts/build-and-deploy#python). Once you have completed the first step in the guide of creating a Cloud Project, go into the console of that Cloud Run project and you will see a button at the top that says `SET UP CONTINUOUS DEPLOYMENT`. From there follow the on-screen prompts to select your GitHub repo that has the Dockerfile and the project will be continuously deployed from that repo. Or alternatively just follow the entire guide that I have linked, which is a more verbose way of deploying.

**Comment by EmreTokyuez** [comment]
Okay gotcha, thanks very much!

How did you save your model? I am stuck saving the vocab from my file but the functions I saw in https://github.com/bentrevett/pytorch-sentiment-analysis/issues/40 result in unpickling errors :/

**Comment by oliverproud** [comment]
Loading the vocab is as simple as:
 ```python 
s3_word_dict_url = 'https://sent-model.s3.eu-west-2.amazonaws.com/word_dict.pkl'
path_to_dict = download_model(s3_word_dict_url, model_name="word_dict.pkl")

with open(path_to_dict, 'rb') as f:
    TEXT = pickle.load(f)
```

The code above is seen in `model.py` from lines 86 to 90. 

Now you mention unpickling errors, that may be because libraries are out of date - try only using the verisons defined in `requirements.txt`.

**Comment by EmreTokyuez** [comment]
How did you save your vocab tho? Just pickle? Cuz I am trying to save my own vocab

**Comment by oliverproud** [comment]
Yes it will have been saved with Pickle. 

Off the top of my head saving it would be something like this: 
```python 

with open('word_dict.pkl', 'wb') as f:
    pickle.dump(TEXT.vocab, f)
```

**Comment by EmreTokyuez** [comment]
This didn't throw an error, thanks! I'll try it with the CNN model later. As my first model is the LSTM mode, I got errors as the model needs unk_idx as well :/

But I am sure I'll be able to deploy my CNN model later, thank you very much!

**Comment by oliverproud** [comment]
You're welcome, glad I could help. 

I'll close this issue now, have fun!
